spring.application.name=task-management-system-backend
server.port=8080
spring.profiles.include=secrets

# Mongodb configuration
spring.data.mongodb.uri=mongodb://localhost:27017/taskmanagementsystem

# JWT configuration
app.jwt.access-token-secret=${JWT_ACCESS_SECRET}
app.jwt.refresh-token-secret=${JWT_REFRESH_SECRET}
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-ms=604800000

# Mail configuration
spring.mail.host=${SPRING_MAIL_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${SPRING_MAIL_PORT:2525}
app.mail.from=${APP_MAIL_FROM:noreply@tasksystem.local}
